-- Add missing TicketStatus values
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'IN_DIAGNOSIS';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'IN_ANALYSIS';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'PENDING_USER';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'PENDING_PROVIDER';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'ESCALATED';

-- Create TicketType enum
DO $$ BEGIN
  CREATE TYPE "TicketType" AS ENUM ('INCIDENT', 'REQUEST', 'ACCESS_PERMISSIONS', 'PURCHASE', 'QUERY', 'PROBLEM', 'CHANGE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Create ImpactLevel enum
DO $$ BEGIN
  CREATE TYPE "ImpactLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Add missing columns to tickets
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "type" "TicketType" NOT NULL DEFAULT 'INCIDENT';
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "impact" "ImpactLevel" NOT NULL DEFAULT 'LOW';
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "subcategory" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "area" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "location" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "affectedSystem" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "appVersion" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "siteType" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "requesterName" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "requesterContact" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "equipmentName" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "deviceType" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "deviceDetail" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "solution" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "slaDeadline" TIMESTAMP(3);
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "slaBreached" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "techCategory" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "affectedAsset" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "assignedGroup" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "urgency" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "diagnosis" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "whatNeeded" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "affectedService" TEXT;
ALTER TABLE "tickets" ADD COLUMN IF NOT EXISTS "createdFromUserView" BOOLEAN NOT NULL DEFAULT false;

-- Update default status from OPEN to NEW
ALTER TABLE "tickets" ALTER COLUMN "status" SET DEFAULT 'NEW';
