-- AlterEnum
ALTER TYPE "AssetType" ADD VALUE 'NVR' BEFORE 'OTHER';
ALTER TYPE "AssetType" ADD VALUE 'SWITCH' BEFORE 'OTHER';
ALTER TYPE "AssetType" ADD VALUE 'ACCESS_POINT' BEFORE 'OTHER';
ALTER TYPE "AssetType" ADD VALUE 'FIREWALL' BEFORE 'OTHER';
ALTER TYPE "AssetType" ADD VALUE 'VIDEOCONFERENCE' BEFORE 'OTHER';
